//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trener.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class objectsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal objectsStrings() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trener.Resources.Languages.objectsStrings", typeof(objectsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ABOUT APP.
        /// </summary>
        internal static string AboutAppButton {
            get {
                return ResourceManager.GetString("AboutAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add counters.
        /// </summary>
        internal static string add_countersText {
            get {
                return ResourceManager.GetString("add_countersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add combo.
        /// </summary>
        internal static string AddCButton {
            get {
                return ResourceManager.GetString("AddCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný All.
        /// </summary>
        internal static string AllButton {
            get {
                return ResourceManager.GetString("AllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Back.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only single punches.
        /// </summary>
        internal static string basic_strikes_introText {
            get {
                return ResourceManager.GetString("basic_strikes_introText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Basic defence.
        /// </summary>
        internal static string BasicDefenceButton {
            get {
                return ResourceManager.GetString("BasicDefenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Basic movement.
        /// </summary>
        internal static string BasicMovementButton {
            get {
                return ResourceManager.GetString("BasicMovementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Basic strikes.
        /// </summary>
        internal static string BasicStrikesButton {
            get {
                return ResourceManager.GetString("BasicStrikesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Body cross.
        /// </summary>
        internal static string BCrossButton {
            get {
                return ResourceManager.GetString("BCrossButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Body jab.
        /// </summary>
        internal static string BJabButton {
            get {
                return ResourceManager.GetString("BJabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Burpees.
        /// </summary>
        internal static string burpees {
            get {
                return ResourceManager.GetString("burpees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Close fighting.
        /// </summary>
        internal static string closefighting {
            get {
                return ResourceManager.GetString("closefighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Combos with movement.
        /// </summary>
        internal static string CMButton {
            get {
                return ResourceManager.GetString("CMButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Combos after movement.
        /// </summary>
        internal static string combos_after_moves {
            get {
                return ResourceManager.GetString("combos_after_moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Counter Puncher.
        /// </summary>
        internal static string CounterPuncherButton {
            get {
                return ResourceManager.GetString("CounterPuncherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lean forward and drop your hands a little.
        /// </summary>
        internal static string CounterpuncherIntro {
            get {
                return ResourceManager.GetString("CounterpuncherIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lean forward and drop your hands a little.
        /// </summary>
        internal static string counterpuncherintroText {
            get {
                return ResourceManager.GetString("counterpuncherintroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only counters.
        /// </summary>
        internal static string countersonly {
            get {
                return ResourceManager.GetString("countersonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cross.
        /// </summary>
        internal static string CrossButton {
            get {
                return ResourceManager.GetString("CrossButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only defence.
        /// </summary>
        internal static string defence_onlyText {
            get {
                return ResourceManager.GetString("defence_onlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Defence.
        /// </summary>
        internal static string DefenceButton {
            get {
                return ResourceManager.GetString("DefenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete combo.
        /// </summary>
        internal static string DelButton {
            get {
                return ResourceManager.GetString("DelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete current combo.
        /// </summary>
        internal static string DelCurButton {
            get {
                return ResourceManager.GetString("DelCurButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Duck.
        /// </summary>
        internal static string DuckButton {
            get {
                return ResourceManager.GetString("DuckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Finish combo with bodyshot.
        /// </summary>
        internal static string finishwithBodyshot {
            get {
                return ResourceManager.GetString("finishwithBodyshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FREESTYLE WORKOUTS.
        /// </summary>
        internal static string FreestyleButton {
            get {
                return ResourceManager.GetString("FreestyleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný High guard.
        /// </summary>
        internal static string hands_high {
            get {
                return ResourceManager.GetString("hands_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only headmovement.
        /// </summary>
        internal static string headmovement_only {
            get {
                return ResourceManager.GetString("headmovement_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dodge and counter.
        /// </summary>
        internal static string headmovementandcounter {
            get {
                return ResourceManager.GetString("headmovementandcounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Inside sidestep.
        /// </summary>
        internal static string ISButton {
            get {
                return ResourceManager.GetString("ISButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jab .
        /// </summary>
        internal static string JabButton {
            get {
                return ResourceManager.GetString("JabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Keep moving.
        /// </summary>
        internal static string keepmoving {
            get {
                return ResourceManager.GetString("keepmoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Keep moving forward.
        /// </summary>
        internal static string keepmovingforward {
            get {
                return ResourceManager.GetString("keepmovingforward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead bodyblock.
        /// </summary>
        internal static string LBBButton {
            get {
                return ResourceManager.GetString("LBBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead hook body.
        /// </summary>
        internal static string LBHook {
            get {
                return ResourceManager.GetString("LBHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead body uppercut.
        /// </summary>
        internal static string LBUpperButton {
            get {
                return ResourceManager.GetString("LBUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead catch.
        /// </summary>
        internal static string LCButton {
            get {
                return ResourceManager.GetString("LCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Longer combos.
        /// </summary>
        internal static string LCombosButton {
            get {
                return ResourceManager.GetString("LCombosButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LEARN TECHNIQUE.
        /// </summary>
        internal static string LearnTechButton {
            get {
                return ResourceManager.GetString("LearnTechButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead hook.
        /// </summary>
        internal static string LHookButton {
            get {
                return ResourceManager.GetString("LHookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Long range fighter.
        /// </summary>
        internal static string LongRangeButton {
            get {
                return ResourceManager.GetString("LongRangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Control distance with your lead hand .
        /// </summary>
        internal static string longrangefighterintro {
            get {
                return ResourceManager.GetString("longrangefighterintro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead parry.
        /// </summary>
        internal static string LPButton {
            get {
                return ResourceManager.GetString("LPButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead roll.
        /// </summary>
        internal static string LRButton {
            get {
                return ResourceManager.GetString("LRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead slip.
        /// </summary>
        internal static string LSlipButton {
            get {
                return ResourceManager.GetString("LSlipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead uppercut.
        /// </summary>
        internal static string LUpperButton {
            get {
                return ResourceManager.GetString("LUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Mix it up.
        /// </summary>
        internal static string mix_it_up {
            get {
                return ResourceManager.GetString("mix_it_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only movement.
        /// </summary>
        internal static string move_only {
            get {
                return ResourceManager.GetString("move_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Move around and jab.
        /// </summary>
        internal static string moveandjab {
            get {
                return ResourceManager.GetString("moveandjab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Movement.
        /// </summary>
        internal static string MovementButton {
            get {
                return ResourceManager.GetString("MovementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Move your head.
        /// </summary>
        internal static string moveyourhead {
            get {
                return ResourceManager.GetString("moveyourhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Make your own workout.
        /// </summary>
        internal static string MYOWorkoutButton {
            get {
                return ResourceManager.GetString("MYOWorkoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only hooks and uppercuts.
        /// </summary>
        internal static string onlyhooksandupper {
            get {
                return ResourceManager.GetString("onlyhooksandupper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only straight punches.
        /// </summary>
        internal static string onlystraightpunches {
            get {
                return ResourceManager.GetString("onlystraightpunches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Outside sidestep.
        /// </summary>
        internal static string OSButton {
            get {
                return ResourceManager.GetString("OSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Outside sidestep.
        /// </summary>
        internal static string Outside_sidestep {
            get {
                return ResourceManager.GetString("Outside sidestep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Plank.
        /// </summary>
        internal static string plank {
            get {
                return ResourceManager.GetString("plank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pressure fighter.
        /// </summary>
        internal static string PressureFighterButton {
            get {
                return ResourceManager.GetString("PressureFighterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pressure.
        /// </summary>
        internal static string pressureFighterIntro {
            get {
                return ResourceManager.GetString("pressureFighterIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Progress.
        /// </summary>
        internal static string ProgressButton {
            get {
                return ResourceManager.GetString("ProgressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Punches.
        /// </summary>
        internal static string PunchesButton {
            get {
                return ResourceManager.GetString("PunchesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pushups.
        /// </summary>
        internal static string pushups {
            get {
                return ResourceManager.GetString("pushups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný QUIT.
        /// </summary>
        internal static string QuitButton {
            get {
                return ResourceManager.GetString("QuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear Bodyblock.
        /// </summary>
        internal static string RBBButton {
            get {
                return ResourceManager.GetString("RBBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear body hook.
        /// </summary>
        internal static string RBHookButton {
            get {
                return ResourceManager.GetString("RBHookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear body uppercut.
        /// </summary>
        internal static string RBUpperButton {
            get {
                return ResourceManager.GetString("RBUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear catch.
        /// </summary>
        internal static string RCButton {
            get {
                return ResourceManager.GetString("RCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear hook.
        /// </summary>
        internal static string RHookButton {
            get {
                return ResourceManager.GetString("RHookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear parry.
        /// </summary>
        internal static string RPButton {
            get {
                return ResourceManager.GetString("RPButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear roll.
        /// </summary>
        internal static string RRButton {
            get {
                return ResourceManager.GetString("RRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear slip.
        /// </summary>
        internal static string RSlipButton {
            get {
                return ResourceManager.GetString("RSlipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear uppercut.
        /// </summary>
        internal static string RUpperButton {
            get {
                return ResourceManager.GetString("RUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save workout.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Shadow boxing.
        /// </summary>
        internal static string shadowboxing {
            get {
                return ResourceManager.GetString("shadowboxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Shadowboxing circuit.
        /// </summary>
        internal static string ShadowboxingButton {
            get {
                return ResourceManager.GetString("ShadowboxingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show workout.
        /// </summary>
        internal static string ShowButton {
            get {
                return ResourceManager.GetString("ShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Situps.
        /// </summary>
        internal static string situps {
            get {
                return ResourceManager.GetString("situps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Skipping rope .
        /// </summary>
        internal static string skippingrope {
            get {
                return ResourceManager.GetString("skippingrope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Skipping rope circuit.
        /// </summary>
        internal static string SkippingRopeButton {
            get {
                return ResourceManager.GetString("SkippingRopeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Squats.
        /// </summary>
        internal static string squats {
            get {
                return ResourceManager.GetString("squats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Start every combo with jab.
        /// </summary>
        internal static string startwithjab {
            get {
                return ResourceManager.GetString("startwithjab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step back.
        /// </summary>
        internal static string StBButton {
            get {
                return ResourceManager.GetString("StBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step forward.
        /// </summary>
        internal static string StFButton {
            get {
                return ResourceManager.GetString("StFButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step left.
        /// </summary>
        internal static string StLButton {
            get {
                return ResourceManager.GetString("StLButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step right.
        /// </summary>
        internal static string StRButton {
            get {
                return ResourceManager.GetString("StRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný STYLES.
        /// </summary>
        internal static string StylesButton {
            get {
                return ResourceManager.GetString("StylesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Switchhitting.
        /// </summary>
        internal static string SwitchHitterButton {
            get {
                return ResourceManager.GetString("SwitchHitterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change language.
        /// </summary>
        internal static string SwitchLangButton {
            get {
                return ResourceManager.GetString("SwitchLangButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Switch stance.
        /// </summary>
        internal static string switchstance {
            get {
                return ResourceManager.GetString("switchstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TECHNIQUE 1.
        /// </summary>
        internal static string Tech1Button {
            get {
                return ResourceManager.GetString("Tech1Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TECHNIQUE 2.
        /// </summary>
        internal static string Tech2Button {
            get {
                return ResourceManager.GetString("Tech2Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Three punch combos with defence.
        /// </summary>
        internal static string three_p_combos_defenceText {
            get {
                return ResourceManager.GetString("three_p_combos_defenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Three punch combos with movement.
        /// </summary>
        internal static string three_p_combos_movementText {
            get {
                return ResourceManager.GetString("three_p_combos_movementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Three punch combos.
        /// </summary>
        internal static string three_p_combosText {
            get {
                return ResourceManager.GetString("three_p_combosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Two punch combos.
        /// </summary>
        internal static string two_p_combosText {
            get {
                return ResourceManager.GetString("two_p_combosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Two punch combos only.
        /// </summary>
        internal static string twopunchcombosonly {
            get {
                return ResourceManager.GetString("twopunchcombosonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Use your lead hand only.
        /// </summary>
        internal static string useonlyleadhand {
            get {
                return ResourceManager.GetString("useonlyleadhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný View your own workouts.
        /// </summary>
        internal static string ViewButton {
            get {
                return ResourceManager.GetString("ViewButton", resourceCulture);
            }
        }
    }
}
