//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trener.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class objectsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal objectsStrings() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trener.Resources.Languages.objectsStrings", typeof(objectsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný INFO.
        /// </summary>
        internal static string AboutAppButton {
            get {
                return ResourceManager.GetString("AboutAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The main purpose of the app is to conduct independent technical training of the trainee, as on the bag or during shadow boxing, it serves as an audiovisual trainer, where it reports and visually shows the user in real time what punches and movements to use. .
        /// </summary>
        internal static string AboutAppDesc {
            get {
                return ResourceManager.GetString("AboutAppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add counters.
        /// </summary>
        internal static string add_countersText {
            get {
                return ResourceManager.GetString("add_countersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Add combo.
        /// </summary>
        internal static string AddCButton {
            get {
                return ResourceManager.GetString("AddCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný All.
        /// </summary>
        internal static string AllButton {
            get {
                return ResourceManager.GetString("AllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Amateur.
        /// </summary>
        internal static string amateur {
            get {
                return ResourceManager.GetString("amateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Back.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only single punches.
        /// </summary>
        internal static string basic_strikes_introText {
            get {
                return ResourceManager.GetString("basic_strikes_introText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Basic defence.
        /// </summary>
        internal static string BasicDefenceButton {
            get {
                return ResourceManager.GetString("BasicDefenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Basic movement.
        /// </summary>
        internal static string BasicMovementButton {
            get {
                return ResourceManager.GetString("BasicMovementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Basic strikes.
        /// </summary>
        internal static string BasicStrikesButton {
            get {
                return ResourceManager.GetString("BasicStrikesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BB - Body Block: Blocking straight punches to the body by keeping elbows together..
        /// </summary>
        internal static string BBDesc {
            get {
                return ResourceManager.GetString("BBDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Body cross.
        /// </summary>
        internal static string BCrossButton {
            get {
                return ResourceManager.GetString("BCrossButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Body jab.
        /// </summary>
        internal static string BJabButton {
            get {
                return ResourceManager.GetString("BJabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 2b - Body Cross: A cross aimed at the opponent’s body..
        /// </summary>
        internal static string BodyCrossDesc {
            get {
                return ResourceManager.GetString("BodyCrossDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 1b - Body Jab: A jab aimed at the opponent’s body..
        /// </summary>
        internal static string BodyJabDesc {
            get {
                return ResourceManager.GetString("BodyJabDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Burpees.
        /// </summary>
        internal static string burpees {
            get {
                return ResourceManager.GetString("burpees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Champion.
        /// </summary>
        internal static string Champ {
            get {
                return ResourceManager.GetString("Champ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Shadowboxing circuit: Shadowboxing + (pushups, squats, burpees).
        /// </summary>
        internal static string Circuit1Desc {
            get {
                return ResourceManager.GetString("Circuit1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Skipping rope circuit: Skipping rope + (pushups, squats, burpees).
        /// </summary>
        internal static string Circuit2Desc {
            get {
                return ResourceManager.GetString("Circuit2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Circuit: A classic circuit training where the user alternates strength exercises with jump rope or freestyle shadowboxing..
        /// </summary>
        internal static string CircuitDesc {
            get {
                return ResourceManager.GetString("CircuitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Close fighting.
        /// </summary>
        internal static string closefighting {
            get {
                return ResourceManager.GetString("closefighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Combos with movement.
        /// </summary>
        internal static string CMButton {
            get {
                return ResourceManager.GetString("CMButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Combos after movement.
        /// </summary>
        internal static string combos_after_moves {
            get {
                return ResourceManager.GetString("combos_after_moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný You&apos;ve completed your workout!.
        /// </summary>
        internal static string completion {
            get {
                return ResourceManager.GetString("completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Counter Puncher.
        /// </summary>
        internal static string CounterPuncherButton {
            get {
                return ResourceManager.GetString("CounterPuncherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lean forward and drop your hands a little.
        /// </summary>
        internal static string CounterpuncherIntro {
            get {
                return ResourceManager.GetString("CounterpuncherIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lean forward and drop your hands a little.
        /// </summary>
        internal static string counterpuncherintroText {
            get {
                return ResourceManager.GetString("counterpuncherintroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only counters.
        /// </summary>
        internal static string countersonly {
            get {
                return ResourceManager.GetString("countersonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Count.
        /// </summary>
        internal static string countText {
            get {
                return ResourceManager.GetString("countText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cross.
        /// </summary>
        internal static string CrossButton {
            get {
                return ResourceManager.GetString("CrossButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 2 - Cross: A powerful straight punch thrown with the rear hand..
        /// </summary>
        internal static string CrossDesc {
            get {
                return ResourceManager.GetString("CrossDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Duck: Squatting to avoid straight punches..
        /// </summary>
        internal static string DDesc {
            get {
                return ResourceManager.GetString("DDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only defence.
        /// </summary>
        internal static string defence_onlyText {
            get {
                return ResourceManager.GetString("defence_onlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Defence.
        /// </summary>
        internal static string DefenceButton {
            get {
                return ResourceManager.GetString("DefenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete combo.
        /// </summary>
        internal static string DelButton {
            get {
                return ResourceManager.GetString("DelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete this workout.
        /// </summary>
        internal static string DelCurButton {
            get {
                return ResourceManager.GetString("DelCurButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Duck.
        /// </summary>
        internal static string DuckButton {
            get {
                return ResourceManager.GetString("DuckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The workout is empty, add at least 1 combo.
        /// </summary>
        internal static string emptyWorkoutError {
            get {
                return ResourceManager.GetString("emptyWorkoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný End.
        /// </summary>
        internal static string endText {
            get {
                return ResourceManager.GetString("endText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Exercise.
        /// </summary>
        internal static string exerciseText {
            get {
                return ResourceManager.GetString("exerciseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Finish combo with bodyshot.
        /// </summary>
        internal static string finishwithBodyshot {
            get {
                return ResourceManager.GetString("finishwithBodyshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Freestyle1: Move around and jab, two punch combos only,Only straight punches, Finish combo with bodyshot, Use your lead hand only, Only hooks and uppercut, Only counters, Closefighting.
        /// </summary>
        internal static string Freestyle1Desc {
            get {
                return ResourceManager.GetString("Freestyle1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Freestyle2: Dodge and counter, Start every combo with jab, Finish combo with bodyshot, Move around and jab, Use you lead hand only, Only hooks and uppercuts,Only counters,.
        /// </summary>
        internal static string Freestyle2Desc {
            get {
                return ResourceManager.GetString("Freestyle2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FREESTYLE WORKOUTS.
        /// </summary>
        internal static string FreestyleButton {
            get {
                return ResourceManager.GetString("FreestyleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Freestyle workout: A workout where user is guided by more general instructions .
        /// </summary>
        internal static string FreestyleDesc {
            get {
                return ResourceManager.GetString("FreestyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Good job!.
        /// </summary>
        internal static string good_job {
            get {
                return ResourceManager.GetString("good_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný High guard.
        /// </summary>
        internal static string hands_high {
            get {
                return ResourceManager.GetString("hands_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only headmovement.
        /// </summary>
        internal static string headmovement_only {
            get {
                return ResourceManager.GetString("headmovement_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dodge and counter.
        /// </summary>
        internal static string headmovementandcounter {
            get {
                return ResourceManager.GetString("headmovementandcounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Inside sidestep.
        /// </summary>
        internal static string ISButton {
            get {
                return ResourceManager.GetString("ISButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ISStep - Inside Sidestep: Avoiding a straight punch by stepping with the lead foot toward the rear side and pivoting..
        /// </summary>
        internal static string ISDesc {
            get {
                return ResourceManager.GetString("ISDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jab .
        /// </summary>
        internal static string JabButton {
            get {
                return ResourceManager.GetString("JabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 1 - Jab: A quick, straight punch with the lead hand, the most commonly used punch in boxing..
        /// </summary>
        internal static string JabDesc {
            get {
                return ResourceManager.GetString("JabDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Keep moving.
        /// </summary>
        internal static string keepmoving {
            get {
                return ResourceManager.GetString("keepmoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Keep moving forward.
        /// </summary>
        internal static string keepmovingforward {
            get {
                return ResourceManager.GetString("keepmovingforward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead bodyblock.
        /// </summary>
        internal static string LBBButton {
            get {
                return ResourceManager.GetString("LBBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LBB - Lead Body Block: Blocking a body hook by tilting toward the lead side..
        /// </summary>
        internal static string LBBDesc {
            get {
                return ResourceManager.GetString("LBBDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LBlock - Lead Block: Blocking a straight punch with the lead hand.
        /// </summary>
        internal static string LBDesc {
            get {
                return ResourceManager.GetString("LBDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead hook body.
        /// </summary>
        internal static string LBHook {
            get {
                return ResourceManager.GetString("LBHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead body uppercut.
        /// </summary>
        internal static string LBUpperButton {
            get {
                return ResourceManager.GetString("LBUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead catch.
        /// </summary>
        internal static string LCButton {
            get {
                return ResourceManager.GetString("LCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LCatch - Lead Catch: Blocking a hook with the lead hand..
        /// </summary>
        internal static string LCDesc {
            get {
                return ResourceManager.GetString("LCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Longer combos.
        /// </summary>
        internal static string LCombosButton {
            get {
                return ResourceManager.GetString("LCombosButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 3b - Lead Body Hook: A lead hook aimed at the opponent’s body..
        /// </summary>
        internal static string LeadBodyHookDesc {
            get {
                return ResourceManager.GetString("LeadBodyHookDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 3 - Lead Hook: A hooking punch thrown with the lead hand..
        /// </summary>
        internal static string LeadHookDesc {
            get {
                return ResourceManager.GetString("LeadHookDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 5 - Lead Uppercut: A rising punch thrown with the lead hand, useful for close-range attacks..
        /// </summary>
        internal static string LeadUpperDesc {
            get {
                return ResourceManager.GetString("LeadUpperDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 5b - Lead Body Uppercut: A lead uppercut targeting the opponent’s body..
        /// </summary>
        internal static string LeadUppperBodyDesc {
            get {
                return ResourceManager.GetString("LeadUppperBodyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LEARN TECHNIQUE.
        /// </summary>
        internal static string LearnTechButton {
            get {
                return ResourceManager.GetString("LearnTechButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead hook.
        /// </summary>
        internal static string LHookButton {
            get {
                return ResourceManager.GetString("LHookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Long range fighter.
        /// </summary>
        internal static string LongRangeButton {
            get {
                return ResourceManager.GetString("LongRangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Control distance with your lead hand .
        /// </summary>
        internal static string longrangefighterintro {
            get {
                return ResourceManager.GetString("longrangefighterintro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead parry.
        /// </summary>
        internal static string LPButton {
            get {
                return ResourceManager.GetString("LPButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead roll.
        /// </summary>
        internal static string LRButton {
            get {
                return ResourceManager.GetString("LRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LRoll - Lead Roll: Avoiding a hook by rolling toward the lead foot..
        /// </summary>
        internal static string LRDesc {
            get {
                return ResourceManager.GetString("LRDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LSlip - Lead Slip: Dodging a straight punch by moving toward the lead foot..
        /// </summary>
        internal static string LSDesc {
            get {
                return ResourceManager.GetString("LSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead slip.
        /// </summary>
        internal static string LSlipButton {
            get {
                return ResourceManager.GetString("LSlipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead uppercut.
        /// </summary>
        internal static string LUpperButton {
            get {
                return ResourceManager.GetString("LUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Mix it up.
        /// </summary>
        internal static string mix_it_up {
            get {
                return ResourceManager.GetString("mix_it_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only movement.
        /// </summary>
        internal static string move_only {
            get {
                return ResourceManager.GetString("move_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Move around and jab.
        /// </summary>
        internal static string moveandjab {
            get {
                return ResourceManager.GetString("moveandjab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Movement.
        /// </summary>
        internal static string Movement {
            get {
                return ResourceManager.GetString("Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Movement.
        /// </summary>
        internal static string MovementButton {
            get {
                return ResourceManager.GetString("MovementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Move your head.
        /// </summary>
        internal static string moveyourhead {
            get {
                return ResourceManager.GetString("moveyourhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný OWN WORKOUTS.
        /// </summary>
        internal static string MYOWorkoutButton {
            get {
                return ResourceManager.GetString("MYOWorkoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Enter name!.
        /// </summary>
        internal static string nameMessage {
            get {
                return ResourceManager.GetString("nameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Name of workout.
        /// </summary>
        internal static string NameOfWorkout {
            get {
                return ResourceManager.GetString("NameOfWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Next round.
        /// </summary>
        internal static string nextRound {
            get {
                return ResourceManager.GetString("nextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only hooks and uppercuts.
        /// </summary>
        internal static string onlyhooksandupper {
            get {
                return ResourceManager.GetString("onlyhooksandupper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Only straight punches.
        /// </summary>
        internal static string onlystraightpunches {
            get {
                return ResourceManager.GetString("onlystraightpunches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný For Orthodox (Right-Handed Boxer): Lead - Left, Rear - Right.
        /// </summary>
        internal static string OrthodoxDesc {
            get {
                return ResourceManager.GetString("OrthodoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Outside sidestep.
        /// </summary>
        internal static string OSButton {
            get {
                return ResourceManager.GetString("OSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný OSStep - Outside Sidestep: Avoiding a straight punch by stepping with the lead foot further to the lead side and pivoting..
        /// </summary>
        internal static string OSDesc {
            get {
                return ResourceManager.GetString("OSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Outside sidestep.
        /// </summary>
        internal static string Outside_sidestep {
            get {
                return ResourceManager.GetString("Outside sidestep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pause.
        /// </summary>
        internal static string pauseText {
            get {
                return ResourceManager.GetString("pauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Plank.
        /// </summary>
        internal static string plank {
            get {
                return ResourceManager.GetString("plank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pressure fighter.
        /// </summary>
        internal static string PressureFighterButton {
            get {
                return ResourceManager.GetString("PressureFighterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pressure.
        /// </summary>
        internal static string pressureFighterIntro {
            get {
                return ResourceManager.GetString("pressureFighterIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Professional.
        /// </summary>
        internal static string pro {
            get {
                return ResourceManager.GetString("pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný PROGRESS.
        /// </summary>
        internal static string ProgressButton {
            get {
                return ResourceManager.GetString("ProgressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Punches.
        /// </summary>
        internal static string PunchesButton {
            get {
                return ResourceManager.GetString("PunchesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pushups.
        /// </summary>
        internal static string pushups {
            get {
                return ResourceManager.GetString("pushups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný QUIT.
        /// </summary>
        internal static string QuitButton {
            get {
                return ResourceManager.GetString("QuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear Bodyblock.
        /// </summary>
        internal static string RBBButton {
            get {
                return ResourceManager.GetString("RBBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RBB - Rear Bodyblock: Blocking a body hook by tilting toward the rear side..
        /// </summary>
        internal static string RBBDesc {
            get {
                return ResourceManager.GetString("RBBDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RBlock - Rear Block: Blocking a straight punch with the rear hand.
        /// </summary>
        internal static string RBDesc {
            get {
                return ResourceManager.GetString("RBDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear body hook.
        /// </summary>
        internal static string RBHookButton {
            get {
                return ResourceManager.GetString("RBHookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear body uppercut.
        /// </summary>
        internal static string RBUpperButton {
            get {
                return ResourceManager.GetString("RBUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear catch.
        /// </summary>
        internal static string RCButton {
            get {
                return ResourceManager.GetString("RCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RCatch- Rear Catch: Blocking a hook with the rear hand..
        /// </summary>
        internal static string RCDesc {
            get {
                return ResourceManager.GetString("RCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 4b - Rear Body Hook: A rear hook aimed at the opponent’s body..
        /// </summary>
        internal static string RearHookBodyDesc {
            get {
                return ResourceManager.GetString("RearHookBodyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 4 - Rear Hook: A hooking punch thrown with the rear hand for more power..
        /// </summary>
        internal static string RearHookDesc {
            get {
                return ResourceManager.GetString("RearHookDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 6b - Rear Body Uppercut: A rear uppercut targeting the opponent’s body..
        /// </summary>
        internal static string RearUpperBodyDesc {
            get {
                return ResourceManager.GetString("RearUpperBodyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 6 - Rear Uppercut: A powerful uppercut thrown with the rear hand..
        /// </summary>
        internal static string RearUpperDesc {
            get {
                return ResourceManager.GetString("RearUpperDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rep.
        /// </summary>
        internal static string repText {
            get {
                return ResourceManager.GetString("repText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear hook.
        /// </summary>
        internal static string RHookButton {
            get {
                return ResourceManager.GetString("RHookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear parry.
        /// </summary>
        internal static string RPButton {
            get {
                return ResourceManager.GetString("RPButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear roll.
        /// </summary>
        internal static string RRButton {
            get {
                return ResourceManager.GetString("RRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RRoll - Rear Roll: Avoiding a hook by rolling toward the rear foot..
        /// </summary>
        internal static string RRDesc {
            get {
                return ResourceManager.GetString("RRDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RSlip - Rear Slip: Dodging a straight punch by moving toward the rear foot..
        /// </summary>
        internal static string RSDesc {
            get {
                return ResourceManager.GetString("RSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear slip.
        /// </summary>
        internal static string RSlipButton {
            get {
                return ResourceManager.GetString("RSlipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear uppercut.
        /// </summary>
        internal static string RUpperButton {
            get {
                return ResourceManager.GetString("RUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save workout.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný StepB - Step Backwards: Moving backwards by stepping with the rear foot first, followed by the lead foot..
        /// </summary>
        internal static string SBDesc {
            get {
                return ResourceManager.GetString("SBDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select a workout.
        /// </summary>
        internal static string SelectAWorkout {
            get {
                return ResourceManager.GetString("SelectAWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Semi-professional.
        /// </summary>
        internal static string semi_pro {
            get {
                return ResourceManager.GetString("semi_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný StepF - Step Forward: Moving forward by stepping with the lead foot first, followed by the rear foot.&quot;.
        /// </summary>
        internal static string SFDesc {
            get {
                return ResourceManager.GetString("SFDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Shadow boxing.
        /// </summary>
        internal static string shadowboxing {
            get {
                return ResourceManager.GetString("shadowboxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Shadowboxing circuit.
        /// </summary>
        internal static string ShadowboxingButton {
            get {
                return ResourceManager.GetString("ShadowboxingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show workout.
        /// </summary>
        internal static string ShowButton {
            get {
                return ResourceManager.GetString("ShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Situps.
        /// </summary>
        internal static string situps {
            get {
                return ResourceManager.GetString("situps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Skipping rope .
        /// </summary>
        internal static string skippingrope {
            get {
                return ResourceManager.GetString("skippingrope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Skipping rope circuit.
        /// </summary>
        internal static string SkippingRopeButton {
            get {
                return ResourceManager.GetString("SkippingRopeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Skip.
        /// </summary>
        internal static string skipText {
            get {
                return ResourceManager.GetString("skipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný StepL - Step Left: Moving left by stepping with left foot first, followed by the right foot..
        /// </summary>
        internal static string SLDesc {
            get {
                return ResourceManager.GetString("SLDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný For Southpaw (Left-Handed Boxer): Lead - Right, Rear - Left.
        /// </summary>
        internal static string SouthpawDesc {
            get {
                return ResourceManager.GetString("SouthpawDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Speed.
        /// </summary>
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Enter speed!.
        /// </summary>
        internal static string speedMessage {
            get {
                return ResourceManager.GetString("speedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Squats.
        /// </summary>
        internal static string squats {
            get {
                return ResourceManager.GetString("squats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný StepR - Step Right: Moving right by stepping with right foot first, followed by the left foot.
        ///.
        /// </summary>
        internal static string SRDesc {
            get {
                return ResourceManager.GetString("SRDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Stance.
        /// </summary>
        internal static string StanceDesc {
            get {
                return ResourceManager.GetString("StanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Start every combo with jab.
        /// </summary>
        internal static string startwithjab {
            get {
                return ResourceManager.GetString("startwithjab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step back.
        /// </summary>
        internal static string StBButton {
            get {
                return ResourceManager.GetString("StBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step forward.
        /// </summary>
        internal static string StFButton {
            get {
                return ResourceManager.GetString("StFButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step left.
        /// </summary>
        internal static string StLButton {
            get {
                return ResourceManager.GetString("StLButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step right.
        /// </summary>
        internal static string StRButton {
            get {
                return ResourceManager.GetString("StRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný STYLES.
        /// </summary>
        internal static string StylesButton {
            get {
                return ResourceManager.GetString("StylesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Switchhitting.
        /// </summary>
        internal static string SwitchHitterButton {
            get {
                return ResourceManager.GetString("SwitchHitterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change language.
        /// </summary>
        internal static string SwitchLangButton {
            get {
                return ResourceManager.GetString("SwitchLangButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Switch stance.
        /// </summary>
        internal static string switchstance {
            get {
                return ResourceManager.GetString("switchstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TECHNIQUE 1.
        /// </summary>
        internal static string Tech1Button {
            get {
                return ResourceManager.GetString("Tech1Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TECHNIQUE 2.
        /// </summary>
        internal static string Tech2Button {
            get {
                return ResourceManager.GetString("Tech2Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Three punch combos with defence.
        /// </summary>
        internal static string three_p_combos_defenceText {
            get {
                return ResourceManager.GetString("three_p_combos_defenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Three punch combos with movement.
        /// </summary>
        internal static string three_p_combos_movementText {
            get {
                return ResourceManager.GetString("three_p_combos_movementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Three punch combos.
        /// </summary>
        internal static string three_p_combosText {
            get {
                return ResourceManager.GetString("three_p_combosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Time.
        /// </summary>
        internal static string timeText {
            get {
                return ResourceManager.GetString("timeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Two punch combos.
        /// </summary>
        internal static string two_p_combosText {
            get {
                return ResourceManager.GetString("two_p_combosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Two punch combos only.
        /// </summary>
        internal static string twopunchcombosonly {
            get {
                return ResourceManager.GetString("twopunchcombosonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Use your lead hand only.
        /// </summary>
        internal static string useonlyleadhand {
            get {
                return ResourceManager.GetString("useonlyleadhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný View your own workouts.
        /// </summary>
        internal static string ViewButton {
            get {
                return ResourceManager.GetString("ViewButton", resourceCulture);
            }
        }
    }
}
