//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trener.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class objects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal objects() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trener.Resources.Languages.objects", typeof(objects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ABOUT APP.
        /// </summary>
        public static string AboutAppButton {
            get {
                return ResourceManager.GetString("AboutAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ADD COMBO.
        /// </summary>
        public static string AddCButton {
            get {
                return ResourceManager.GetString("AddCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ALL.
        /// </summary>
        public static string AllButton {
            get {
                return ResourceManager.GetString("AllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BACK.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BASIC DEFENCE.
        /// </summary>
        public static string BasicDefenceButton {
            get {
                return ResourceManager.GetString("BasicDefenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BASIC MOVEMENT.
        /// </summary>
        public static string BasicMovementButton {
            get {
                return ResourceManager.GetString("BasicMovementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BASIC STRIKES.
        /// </summary>
        public static string BasicStrikesButton {
            get {
                return ResourceManager.GetString("BasicStrikesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Body cross.
        /// </summary>
        public static string BCrossButton {
            get {
                return ResourceManager.GetString("BCrossButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Body jab.
        /// </summary>
        public static string BJabButton {
            get {
                return ResourceManager.GetString("BJabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Combos with movement.
        /// </summary>
        public static string CMButton {
            get {
                return ResourceManager.GetString("CMButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Counterpuncher.
        /// </summary>
        public static string CounterPuncherButton {
            get {
                return ResourceManager.GetString("CounterPuncherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Cross.
        /// </summary>
        public static string CrossButton {
            get {
                return ResourceManager.GetString("CrossButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Defence.
        /// </summary>
        public static string DefenceButton {
            get {
                return ResourceManager.GetString("DefenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete combo.
        /// </summary>
        public static string DelButton {
            get {
                return ResourceManager.GetString("DelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Delete current workout.
        /// </summary>
        public static string DelCurButton {
            get {
                return ResourceManager.GetString("DelCurButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný FREESTYLE WORKOUTS.
        /// </summary>
        public static string FreestyleButton {
            get {
                return ResourceManager.GetString("FreestyleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný HEADMOVEMENT.
        /// </summary>
        public static string HMButton {
            get {
                return ResourceManager.GetString("HMButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Inside sidestep.
        /// </summary>
        public static string ISButton {
            get {
                return ResourceManager.GetString("ISButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jab.
        /// </summary>
        public static string JabButton {
            get {
                return ResourceManager.GetString("JabButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead bodyblock.
        /// </summary>
        public static string LBBButton {
            get {
                return ResourceManager.GetString("LBBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Body jab.
        /// </summary>
        public static string LBHook {
            get {
                return ResourceManager.GetString("LBHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead body uppercut.
        /// </summary>
        public static string LBUpperButton {
            get {
                return ResourceManager.GetString("LBUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead catch.
        /// </summary>
        public static string LCButton {
            get {
                return ResourceManager.GetString("LCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Longer Combos.
        /// </summary>
        public static string LCombosButton {
            get {
                return ResourceManager.GetString("LCombosButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LEARN TECHNIQUE.
        /// </summary>
        public static string LearnTechButton {
            get {
                return ResourceManager.GetString("LearnTechButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LEAD HOOK.
        /// </summary>
        public static string LHookButton {
            get {
                return ResourceManager.GetString("LHookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný LONG RANGE FIGHTER.
        /// </summary>
        public static string LongRangeButton {
            get {
                return ResourceManager.GetString("LongRangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead parry.
        /// </summary>
        public static string LPButton {
            get {
                return ResourceManager.GetString("LPButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead roll.
        /// </summary>
        public static string LRButton {
            get {
                return ResourceManager.GetString("LRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead slip.
        /// </summary>
        public static string LSlipButton {
            get {
                return ResourceManager.GetString("LSlipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Lead uppercut.
        /// </summary>
        public static string LUpperButton {
            get {
                return ResourceManager.GetString("LUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Movement.
        /// </summary>
        public static string MovementButton {
            get {
                return ResourceManager.GetString("MovementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CREATE YOUR OWN WORKOUT.
        /// </summary>
        public static string MYOWorkoutButton {
            get {
                return ResourceManager.GetString("MYOWorkoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Outside sidestep.
        /// </summary>
        public static string OSButton {
            get {
                return ResourceManager.GetString("OSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pressure Fighter.
        /// </summary>
        public static string PressureFighterButton {
            get {
                return ResourceManager.GetString("PressureFighterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Progress.
        /// </summary>
        public static string ProgressButton {
            get {
                return ResourceManager.GetString("ProgressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Punches.
        /// </summary>
        public static string PunchesButton {
            get {
                return ResourceManager.GetString("PunchesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný QUIT.
        /// </summary>
        public static string QuitButton {
            get {
                return ResourceManager.GetString("QuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear bodyblock.
        /// </summary>
        public static string RBBButton {
            get {
                return ResourceManager.GetString("RBBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear body hook.
        /// </summary>
        public static string RBHook {
            get {
                return ResourceManager.GetString("RBHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear body uppercut.
        /// </summary>
        public static string RBUpperButton {
            get {
                return ResourceManager.GetString("RBUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear catch.
        /// </summary>
        public static string RCButton {
            get {
                return ResourceManager.GetString("RCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear hook.
        /// </summary>
        public static string RHookButton {
            get {
                return ResourceManager.GetString("RHookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear parry.
        /// </summary>
        public static string RPButton {
            get {
                return ResourceManager.GetString("RPButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear roll.
        /// </summary>
        public static string RRButton {
            get {
                return ResourceManager.GetString("RRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear slip.
        /// </summary>
        public static string RSlipButton {
            get {
                return ResourceManager.GetString("RSlipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rear uppercut.
        /// </summary>
        public static string RUpperButton {
            get {
                return ResourceManager.GetString("RUpperButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Save workout.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Shadowboxing circuit.
        /// </summary>
        public static string ShadowboxingButton {
            get {
                return ResourceManager.GetString("ShadowboxingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný View workout.
        /// </summary>
        public static string ShowButton {
            get {
                return ResourceManager.GetString("ShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Skipping rope circuit.
        /// </summary>
        public static string SkippingRopeButton {
            get {
                return ResourceManager.GetString("SkippingRopeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step back.
        /// </summary>
        public static string StBButton {
            get {
                return ResourceManager.GetString("StBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step forward.
        /// </summary>
        public static string StFButton {
            get {
                return ResourceManager.GetString("StFButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step left.
        /// </summary>
        public static string StLButton {
            get {
                return ResourceManager.GetString("StLButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Step right.
        /// </summary>
        public static string StRButton {
            get {
                return ResourceManager.GetString("StRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný STYLES.
        /// </summary>
        public static string StylesButton {
            get {
                return ResourceManager.GetString("StylesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný SWITCHHITTER.
        /// </summary>
        public static string SwitchHitterButton {
            get {
                return ResourceManager.GetString("SwitchHitterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Change language.
        /// </summary>
        public static string SwitchLangButton {
            get {
                return ResourceManager.GetString("SwitchLangButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TECHNIQUE.
        /// </summary>
        public static string Tech1Button {
            get {
                return ResourceManager.GetString("Tech1Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný TECHNIQUE 2.
        /// </summary>
        public static string Tech2Button {
            get {
                return ResourceManager.GetString("Tech2Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Show own workouts.
        /// </summary>
        public static string ViewButton {
            get {
                return ResourceManager.GetString("ViewButton", resourceCulture);
            }
        }
    }
}
